stefanius_national_holiday_homepage:
    path:     /
    defaults: { _controller: StefaniusNationalHolidayBundle:Default:index }

stefanius_national_holiday_list_all:
    path:     /overzicht
    defaults: { _controller: StefaniusNationalHolidayBundle:Default:list }